# Generated by Django 4.2.5 on 2023-10-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pokemon', models.CharField(max_length=200)),
                ('Raridade', models.CharField(max_length=200)),
                ('Coleção', models.CharField(max_length=200)),
            ],
        ),
    ]
